# :root {
# #6785cc #2a303f
#    --main-color: #2a303f;
#    --back-color: #6785cc;
#}


font=JetBrainsMonoNerdFont-Regular:style=italic

[colors]
background=6785ccff
text=2a303fff
message=2a303fff
selection=b2cfeeff
input=2a303fff
selection-text=2a303fff
border=2a303fff

[border]
radius=15

